# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IwJMdAgB3ZZXAxQG0aKwSkJn6Jcssdy1
"""

# !pip install paho-mqtt

import ssl

import paho.mqtt.client as mqtt

import csv
import json

from time import sleep

from random import choice

from random import seed

CA = '/content/AmazonRootCA1.pem'

CERTI = '/content/5c2039a209a4954b62255b78ac83db96a08e34fb6ffe4399e3dfabab970dc3a5-certificate.pem.crt'

KEYFILE = '/content/5c2039a209a4954b62255b78ac83db96a08e34fb6ffe4399e3dfabab970dc3a5-private.pem.key'

global count

count = 0


def getSensorData():

    with open('/content/forestfires.csv') as csvfile:

        readCSV = list(csv.reader(csvfile, delimiter=','))

        row_you_want = readCSV[count]

        return("Temp : " + str(row_you_want[8]))


mqtt = mqtt.Client()

mqtt.tls_set(CA, CERTI, KEYFILE, cert_reqs=ssl.CERT_REQUIRED,
             tls_version=ssl.PROTOCOL_TLSv1_2, ciphers=None)

mqtt.connect("aodvtbg6443kp-ats.iot.ap-south-1.amazonaws.com", 8883, 60)


mqtt.loop_start()


c = 0


def main():

    global count

    count = 0

    print('Starting...')

    while True:

        count = count + 1

        T = getSensorData()

        print(T)

        mqtt.publish("general/inbound", json.dumps(T), 1)

        sleep(1)


main()

# from google.colab import drive
# drive.mount('/content/drive')
