# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GeqEHSpWY0hc2r-xVr3HiHN0URx4cEXh
"""

# !pip install paho-mqtt

import paho.mqtt.client as mqtt
import ssl

CA = '/content/AmazonRootCA1.pem'
CERTI = '/content/5c2039a209a4954b62255b78ac83db96a08e34fb6ffe4399e3dfabab970dc3a5-certificate.pem.crt'
KEYFILE = '/content/5c2039a209a4954b62255b78ac83db96a08e34fb6ffe4399e3dfabab970dc3a5-private.pem.key'


def on_connect(c, u, f, rc):
    print("resource code" + str(rc))
    mqtt.subscribe("general/inbound", 0)


def on_message(c, u, msg):
    data = (msg.payload).decode("utf-8")
    print(data)


mqtt = mqtt.Client()
mqtt.tls_set(CA, CERTI, KEYFILE, cert_reqs=ssl.CERT_REQUIRED,
             tls_version=ssl.PROTOCOL_TLSv1_2, ciphers=None)
mqtt.connect("aodvtbg6443kp-ats.iot.ap-south-1.amazonaws.com", 8883, 60)

mqtt.on_connect = on_connect
mqtt.on_message = on_message
mqtt.loop_forever()


# from google.colab import drive
# drive.mount('/content/drive')
